### ISSUE TITLE
Failure to deploy FPMM in some config of Ganache

### ISSUE THREAD

**Issue by cag** [gnosis/conditional-tokens-market-makers#30] opened 2020-01-20 16:47 UTC
See #29 for the original context of this issue. I cannot reproduce this error though. From @fvictorio:

> I get an error when using 9/10 outcomes:
> 
> Runtime Error: revert
> Revert reason: create2 failed
> Doesn't happen for 6 or less. I didn't test it with 7 or 8 outcomes so I don't know exactly at which point it stops working, but I can find out if it can help you.
> 
> I tested this in ganache so I don't have a link to the failing transaction, but can do it if you want.

> These are the arguments that are triggering the error in ganache:
> 
> ```
> salt: 79932
> conditionalTokens: 0xD86C8F0327494034F60e25074420BcCF560D5610
> collateralToken: 0x9561C133DD8580860B6b7E504bC5Aa500f0f06a7
> conditionIds: ["0xc64342d07a96343f150eab7da7d653af79431b0c8e5af72a898b0d99eb87112f"]
> gas: 4% (expressed over 1e18)
> initialFunding: 0
> distributionHint: []
> ```

> Ok, now I really can confirm it works on Rinkeby for 10 outcomes:

**Comment by auryn-macmillan** [comment] 2020-07-24 02:15
I'm going to go ahead and close this one since it is almost six months old and apparently couldn't be reproduced at the time.
We can re-open it if it comes back up.

**Closed by auryn-macmillan** 2020-07-24 02:15 UTC
Labels: bug
